# Generated by Django 4.2.6 on 2023-12-06 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyerapp', '0007_alter_products_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category_c', to='flyerapp.products')),
            ],
        ),
    ]
