# Generated by Django 4.2.6 on 2023-12-06 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flyerapp', '0008_category_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pname',
            new_name='prod',
        ),
        migrations.AddField(
            model_name='order',
            name='cats',
            field=models.ManyToManyField(to='flyerapp.category_c'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='pending', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='usr_cos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category_c',
            name='cate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
