# Generated by Django 4.2.6 on 2023-12-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyerapp', '0010_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cats',
        ),
        migrations.AddField(
            model_name='products',
            name='cats',
            field=models.ManyToManyField(to='flyerapp.category_c'),
        ),
    ]
