# Generated by Django 4.2.6 on 2023-12-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyerapp', '0011_remove_order_cats_products_cats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_images',
            field=models.ImageField(null=True, upload_to='static/dbfl'),
        ),
    ]
