# Generated by Django 4.2.6 on 2023-12-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyerapp', '0012_alter_products_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
