# Generated by Django 4.2.6 on 2023-12-07 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flyerapp', '0013_alter_products_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='carte',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_images',
            field=models.ImageField(null=True, upload_to='dbfl'),
        ),
    ]
